name: Auto approve dependabot PRs

on: pull_request_target

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: hmarr/auto-approve-action@v4.0.0
