name: Publish Docs

on:
  workflow_dispatch: { }
  workflow_run:
    workflows: [ "Release (Production)" ]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: self-hosted
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build tplprev
        run: devbox run -- task tplprev
      - name: Generate docs
        run: devbox run -- mkdocs gh-deploy --force --strict
