name: Publish Docs

on:
  workflow_dispatch: { }
  workflow_run:
    workflows: [ "Release (Production)" ]
    types:
      - completed

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: [self-hosted, x64]
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10  # v6.0.3
        with:
          fetch-depth: 0
      - name: Build tplprev
        run: devbox run -- task tplprev
      - name: Install docs dependencies
        run: devbox run -- pip install -r docs-requirements.txt
      - name: Generate docs
        run: devbox run -- mkdocs gh-deploy --force --strict
