name: Publish Docs

on:
  workflow_dispatch: { }
  workflow_run:
    workflows: [ "Release (Production)" ]
    branches: [ main ]
    types:
      - completed

jobs:
  publish-docs:
    name: Publish Docs
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Build tplprev
        run: devbox run -- task tplprev
      - name: Generate docs
        run: devbox run -- mkdocs gh-deploy --strict
