name: Pull Request

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: "true"
      - name: Lint
        run: devbox run -- task lint
  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: "true"
      - name: Run tests
        run: devbox run -- task test
      - name: Publish coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.out
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: "true"
      - name: Build binary
        run: devbox run -- task build
